require:
  - rubocop

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  SuggestExtensions: false

AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
