version: "3.8"
services:
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/frank_calendar
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    ports:
      - "4567:4567"
    environment:
      DATABASE: ${DATABASE}
      POSTGRES_HOST:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      TZ: America/Sao_Paulo
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_HOST:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
