default: &default
  host: <%= ENV['POSTGRES_HOST'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
development:
  <<: *default
  dbname: frankcalendar_development
test:
  <<: *default
  dbname: frankcalendar_test
